spring.application.name=artesanato-erp-api
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# MongoDB Configuration
spring.mongodb.uri=mongodb://root:secret@localhost:27017/mydatabase
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret